version: '3.9'

networks:
  client_a_net:
    driver: overlay
  client_b_net:
    driver: overlay
  proxy_net:
    driver: overlay

volumes:
  client_a_data:
  client_b_data:


configs:
  client_a_config:
    external: true
  client_b_config:
    external: true
  nginx_proxy_config:
    file: ./nginx.conf
services:
  client-a-node-app:
    image: riturajroy589/devops-sample-nest:v1
    networks: [client_a_net, proxy_net]
    configs:
      - source: client_a_config
        target: /app/.env
    volumes:
      - client_a_data:/app/data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  client-b-python-app:
    image: riturajroy589/devops-sample-fast:v1
    networks: [client_b_net, proxy_net]
    configs:
      - source: client_b_config
        target: /app/.env
    volumes:
      - client_b_data:/app/data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/health')\""]
      interval: 30s
      timeout: 10s
      retries: 3
  nginx:
    image: nginx:alpine
    networks:
      - proxy_net
    ports:
      - "80:80"
    configs:
      - source: nginx_proxy_config
        target: /etc/nginx/nginx.conf
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
