version: '3.9'

networks:
  client_a_net:
    driver: overlay
  client_b_net:
    driver: overlay
  proxy_net:
    driver: overlay

volumes:
  client_a_data:
  client_b_data:
  prometheus_data:   # Moved here!
  grafana_data:      # Moved here!
  loki_data:

configs:
  client_a_config:
    external: true
  client_b_config:
    external: true
  nginx_proxy_config:
    file: ./nginx.conf

services:
  client-a-node-app:
    image: riturajroy589/devops-sample-nest:v1
    networks: [client_a_net, proxy_net]
    configs:
      - source: client_a_config
        target: /app/.env
    volumes:
      - client_a_data:/app/data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  client-b-python-app:
    image: riturajroy589/devops-sample-fast:v1
    networks: [client_b_net, proxy_net]
    configs:
      - source: client_b_config
        target: /app/.env
    volumes:
      - client_b_data:/app/data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    healthcheck:    # Fixed indentation!
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/health')\""]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    networks:
      - proxy_net
    ports:
      - "80:80"
    configs:
      - source: nginx_proxy_config
        target: /etc/nginx/nginx.conf
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  # -------------------------------------------
  # MONITORING STACK
  # -------------------------------------------
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - /home/ubuntu/docker-project-main/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    deploy:
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3001:3000" 
    deploy:
      placement:
        constraints:
          - node.role == manager

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      # Removed the problematic /dev/disk mount
    deploy:
      mode: global

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    deploy:
      placement:
        constraints:
          - node.role == manager
  promtail:
    image: grafana/promtail:latest
    volumes:
      # Reading logs directly from your newly attached EBS volume
      - /mnt/data-drive/docker/containers:/mnt/data-drive/docker/containers:ro
      - /home/ubuntu/docker-project-main/promtail.yml:/etc/promtail/promtail.yml:ro
    command: -config.file=/etc/promtail/promtail.yml
    deploy:
      mode: global
